// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XMsgCom.proto

#include "XMsgCom.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace xmsg {

inline constexpr XMsgHead::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        servername_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        msgsize_{0},
        msgtype_{static_cast< ::xmsg::MsgType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR XMsgHead::XMsgHead(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct XMsgHeadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XMsgHeadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~XMsgHeadDefaultTypeInternal() {}
  union {
    XMsgHead _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XMsgHeadDefaultTypeInternal _XMsgHead_default_instance_;

inline constexpr XLoginRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        restype_{static_cast< ::xmsg::XLoginRes_XLoginResType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR XLoginRes::XLoginRes(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct XLoginResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XLoginResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~XLoginResDefaultTypeInternal() {}
  union {
    XLoginRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XLoginResDefaultTypeInternal _XLoginRes_default_instance_;

inline constexpr XLoginReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : username_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR XLoginReq::XLoginReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct XLoginReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XLoginReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~XLoginReqDefaultTypeInternal() {}
  union {
    XLoginReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XLoginReqDefaultTypeInternal _XLoginReq_default_instance_;

inline constexpr XDirRes_XDir::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        filesize_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR XDirRes_XDir::XDirRes_XDir(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct XDirRes_XDirDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XDirRes_XDirDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~XDirRes_XDirDefaultTypeInternal() {}
  union {
    XDirRes_XDir _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XDirRes_XDirDefaultTypeInternal _XDirRes_XDir_default_instance_;

inline constexpr XDirReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR XDirReq::XDirReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct XDirReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XDirReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~XDirReqDefaultTypeInternal() {}
  union {
    XDirReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XDirReqDefaultTypeInternal _XDirReq_default_instance_;

inline constexpr XDirRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : dirs_{},
        restype_{static_cast< ::xmsg::XDirRes_XDirType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR XDirRes::XDirRes(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct XDirResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XDirResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~XDirResDefaultTypeInternal() {}
  union {
    XDirRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XDirResDefaultTypeInternal _XDirRes_default_instance_;
}  // namespace xmsg
static ::_pb::Metadata file_level_metadata_XMsgCom_2eproto[6];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_XMsgCom_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_XMsgCom_2eproto = nullptr;
const ::uint32_t TableStruct_XMsgCom_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::xmsg::XMsgHead, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::xmsg::XMsgHead, _impl_.msgsize_),
    PROTOBUF_FIELD_OFFSET(::xmsg::XMsgHead, _impl_.msgtype_),
    PROTOBUF_FIELD_OFFSET(::xmsg::XMsgHead, _impl_.token_),
    PROTOBUF_FIELD_OFFSET(::xmsg::XMsgHead, _impl_.servername_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::xmsg::XLoginReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::xmsg::XLoginReq, _impl_.username_),
    PROTOBUF_FIELD_OFFSET(::xmsg::XLoginReq, _impl_.password_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::xmsg::XLoginRes, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::xmsg::XLoginRes, _impl_.restype_),
    PROTOBUF_FIELD_OFFSET(::xmsg::XLoginRes, _impl_.token_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::xmsg::XDirReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::xmsg::XDirReq, _impl_.path_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::xmsg::XDirRes_XDir, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::xmsg::XDirRes_XDir, _impl_.filename_),
    PROTOBUF_FIELD_OFFSET(::xmsg::XDirRes_XDir, _impl_.filesize_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::xmsg::XDirRes, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::xmsg::XDirRes, _impl_.restype_),
    PROTOBUF_FIELD_OFFSET(::xmsg::XDirRes, _impl_.dirs_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::xmsg::XMsgHead)},
        {12, -1, -1, sizeof(::xmsg::XLoginReq)},
        {22, -1, -1, sizeof(::xmsg::XLoginRes)},
        {32, -1, -1, sizeof(::xmsg::XDirReq)},
        {41, -1, -1, sizeof(::xmsg::XDirRes_XDir)},
        {51, -1, -1, sizeof(::xmsg::XDirRes)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::xmsg::_XMsgHead_default_instance_._instance,
    &::xmsg::_XLoginReq_default_instance_._instance,
    &::xmsg::_XLoginRes_default_instance_._instance,
    &::xmsg::_XDirReq_default_instance_._instance,
    &::xmsg::_XDirRes_XDir_default_instance_._instance,
    &::xmsg::_XDirRes_default_instance_._instance,
};
const char descriptor_table_protodef_XMsgCom_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\rXMsgCom.proto\022\004xmsg\032\016XMsgType.proto\"^\n"
    "\010XMsgHead\022\017\n\007msgSize\030\001 \001(\005\022\036\n\007msgType\030\002 "
    "\001(\0162\r.xmsg.MsgType\022\r\n\005token\030\003 \001(\t\022\022\n\nser"
    "verName\030\004 \001(\t\"/\n\tXLoginReq\022\020\n\010username\030\001"
    " \001(\t\022\020\n\010password\030\002 \001(\t\"\205\001\n\tXLoginRes\022.\n\007"
    "resType\030\001 \001(\0162\035.xmsg.XLoginRes.XLoginRes"
    "Type\022\r\n\005token\030\002 \001(\t\"9\n\rXLoginResType\022\n\n\006"
    "XRT_OK\020\000\022\013\n\007XRT_ERR\020\001\022\017\n\013XRT_NO_USER\020\002\"\027"
    "\n\007XDirReq\022\014\n\004path\030\001 \001(\t\"\266\001\n\007XDirRes\022\'\n\007r"
    "esType\030\001 \001(\0162\026.xmsg.XDirRes.XDirType\022 \n\004"
    "dirs\030\002 \003(\0132\022.xmsg.XDirRes.XDir\032*\n\004XDir\022\020"
    "\n\010filename\030\001 \001(\t\022\020\n\010filesize\030\002 \001(\005\"4\n\010XD"
    "irType\022\n\n\006XDT_OK\020\000\022\r\n\tXDT_ERROR\020\001\022\r\n\tXDT"
    "_NODIR\020\002b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_XMsgCom_2eproto_deps[1] =
    {
        &::descriptor_table_XMsgType_2eproto,
};
static ::absl::once_flag descriptor_table_XMsgCom_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_XMsgCom_2eproto = {
    false,
    false,
    536,
    descriptor_table_protodef_XMsgCom_2eproto,
    "XMsgCom.proto",
    &descriptor_table_XMsgCom_2eproto_once,
    descriptor_table_XMsgCom_2eproto_deps,
    1,
    6,
    schemas,
    file_default_instances,
    TableStruct_XMsgCom_2eproto::offsets,
    file_level_metadata_XMsgCom_2eproto,
    file_level_enum_descriptors_XMsgCom_2eproto,
    file_level_service_descriptors_XMsgCom_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_XMsgCom_2eproto_getter() {
  return &descriptor_table_XMsgCom_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_XMsgCom_2eproto(&descriptor_table_XMsgCom_2eproto);
namespace xmsg {
const ::google::protobuf::EnumDescriptor* XLoginRes_XLoginResType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_XMsgCom_2eproto);
  return file_level_enum_descriptors_XMsgCom_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t XLoginRes_XLoginResType_internal_data_[] = {
    196608u, 0u, };
bool XLoginRes_XLoginResType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr XLoginRes_XLoginResType XLoginRes::XRT_OK;
constexpr XLoginRes_XLoginResType XLoginRes::XRT_ERR;
constexpr XLoginRes_XLoginResType XLoginRes::XRT_NO_USER;
constexpr XLoginRes_XLoginResType XLoginRes::XLoginResType_MIN;
constexpr XLoginRes_XLoginResType XLoginRes::XLoginResType_MAX;
constexpr int XLoginRes::XLoginResType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::google::protobuf::EnumDescriptor* XDirRes_XDirType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_XMsgCom_2eproto);
  return file_level_enum_descriptors_XMsgCom_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t XDirRes_XDirType_internal_data_[] = {
    196608u, 0u, };
bool XDirRes_XDirType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr XDirRes_XDirType XDirRes::XDT_OK;
constexpr XDirRes_XDirType XDirRes::XDT_ERROR;
constexpr XDirRes_XDirType XDirRes::XDT_NODIR;
constexpr XDirRes_XDirType XDirRes::XDirType_MIN;
constexpr XDirRes_XDirType XDirRes::XDirType_MAX;
constexpr int XDirRes::XDirType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class XMsgHead::_Internal {
 public:
};

XMsgHead::XMsgHead(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:xmsg.XMsgHead)
}
inline PROTOBUF_NDEBUG_INLINE XMsgHead::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : token_(arena, from.token_),
        servername_(arena, from.servername_),
        _cached_size_{0} {}

XMsgHead::XMsgHead(
    ::google::protobuf::Arena* arena,
    const XMsgHead& from)
    : ::google::protobuf::Message(arena) {
  XMsgHead* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, msgsize_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, msgsize_),
           offsetof(Impl_, msgtype_) -
               offsetof(Impl_, msgsize_) +
               sizeof(Impl_::msgtype_));

  // @@protoc_insertion_point(copy_constructor:xmsg.XMsgHead)
}
inline PROTOBUF_NDEBUG_INLINE XMsgHead::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : token_(arena),
        servername_(arena),
        _cached_size_{0} {}

inline void XMsgHead::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, msgsize_),
           0,
           offsetof(Impl_, msgtype_) -
               offsetof(Impl_, msgsize_) +
               sizeof(Impl_::msgtype_));
}
XMsgHead::~XMsgHead() {
  // @@protoc_insertion_point(destructor:xmsg.XMsgHead)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void XMsgHead::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.token_.Destroy();
  _impl_.servername_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void XMsgHead::Clear() {
// @@protoc_insertion_point(message_clear_start:xmsg.XMsgHead)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_.ClearToEmpty();
  _impl_.servername_.ClearToEmpty();
  ::memset(&_impl_.msgsize_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.msgtype_) -
      reinterpret_cast<char*>(&_impl_.msgsize_)) + sizeof(_impl_.msgtype_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* XMsgHead::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 37, 2> XMsgHead::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_XMsgHead_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string serverName = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.servername_)}},
    // int32 msgSize = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(XMsgHead, _impl_.msgsize_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgsize_)}},
    // .xmsg.MsgType msgType = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(XMsgHead, _impl_.msgtype_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgtype_)}},
    // string token = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.token_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 msgSize = 1;
    {PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgsize_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .xmsg.MsgType msgType = 2;
    {PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgtype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string token = 3;
    {PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string serverName = 4;
    {PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.servername_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\0\0\5\12\0\0\0"
    "xmsg.XMsgHead"
    "token"
    "serverName"
  }},
};

::uint8_t* XMsgHead::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xmsg.XMsgHead)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 msgSize = 1;
  if (this->_internal_msgsize() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_msgsize(), target);
  }

  // .xmsg.MsgType msgType = 2;
  if (this->_internal_msgtype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_msgtype(), target);
  }

  // string token = 3;
  if (!this->_internal_token().empty()) {
    const std::string& _s = this->_internal_token();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "xmsg.XMsgHead.token");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string serverName = 4;
  if (!this->_internal_servername().empty()) {
    const std::string& _s = this->_internal_servername();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "xmsg.XMsgHead.serverName");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xmsg.XMsgHead)
  return target;
}

::size_t XMsgHead::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xmsg.XMsgHead)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string token = 3;
  if (!this->_internal_token().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_token());
  }

  // string serverName = 4;
  if (!this->_internal_servername().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_servername());
  }

  // int32 msgSize = 1;
  if (this->_internal_msgsize() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_msgsize());
  }

  // .xmsg.MsgType msgType = 2;
  if (this->_internal_msgtype() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_msgtype());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData XMsgHead::_class_data_ = {
    XMsgHead::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* XMsgHead::GetClassData() const {
  return &_class_data_;
}

void XMsgHead::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<XMsgHead*>(&to_msg);
  auto& from = static_cast<const XMsgHead&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xmsg.XMsgHead)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (!from._internal_servername().empty()) {
    _this->_internal_set_servername(from._internal_servername());
  }
  if (from._internal_msgsize() != 0) {
    _this->_internal_set_msgsize(from._internal_msgsize());
  }
  if (from._internal_msgtype() != 0) {
    _this->_internal_set_msgtype(from._internal_msgtype());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void XMsgHead::CopyFrom(const XMsgHead& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xmsg.XMsgHead)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool XMsgHead::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* XMsgHead::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void XMsgHead::InternalSwap(XMsgHead* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.servername_, &other->_impl_.servername_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgtype_)
      + sizeof(XMsgHead::_impl_.msgtype_)
      - PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgsize_)>(
          reinterpret_cast<char*>(&_impl_.msgsize_),
          reinterpret_cast<char*>(&other->_impl_.msgsize_));
}

::google::protobuf::Metadata XMsgHead::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_XMsgCom_2eproto_getter, &descriptor_table_XMsgCom_2eproto_once,
      file_level_metadata_XMsgCom_2eproto[0]);
}
// ===================================================================

class XLoginReq::_Internal {
 public:
};

XLoginReq::XLoginReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:xmsg.XLoginReq)
}
inline PROTOBUF_NDEBUG_INLINE XLoginReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : username_(arena, from.username_),
        password_(arena, from.password_),
        _cached_size_{0} {}

XLoginReq::XLoginReq(
    ::google::protobuf::Arena* arena,
    const XLoginReq& from)
    : ::google::protobuf::Message(arena) {
  XLoginReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:xmsg.XLoginReq)
}
inline PROTOBUF_NDEBUG_INLINE XLoginReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : username_(arena),
        password_(arena),
        _cached_size_{0} {}

inline void XLoginReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
XLoginReq::~XLoginReq() {
  // @@protoc_insertion_point(destructor:xmsg.XLoginReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void XLoginReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.username_.Destroy();
  _impl_.password_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void XLoginReq::Clear() {
// @@protoc_insertion_point(message_clear_start:xmsg.XLoginReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.username_.ClearToEmpty();
  _impl_.password_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* XLoginReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 39, 2> XLoginReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_XLoginReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string password = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(XLoginReq, _impl_.password_)}},
    // string username = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(XLoginReq, _impl_.username_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string username = 1;
    {PROTOBUF_FIELD_OFFSET(XLoginReq, _impl_.username_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string password = 2;
    {PROTOBUF_FIELD_OFFSET(XLoginReq, _impl_.password_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\10\10\0\0\0\0\0"
    "xmsg.XLoginReq"
    "username"
    "password"
  }},
};

::uint8_t* XLoginReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xmsg.XLoginReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string username = 1;
  if (!this->_internal_username().empty()) {
    const std::string& _s = this->_internal_username();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "xmsg.XLoginReq.username");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string password = 2;
  if (!this->_internal_password().empty()) {
    const std::string& _s = this->_internal_password();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "xmsg.XLoginReq.password");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xmsg.XLoginReq)
  return target;
}

::size_t XLoginReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xmsg.XLoginReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string username = 1;
  if (!this->_internal_username().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_username());
  }

  // string password = 2;
  if (!this->_internal_password().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_password());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData XLoginReq::_class_data_ = {
    XLoginReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* XLoginReq::GetClassData() const {
  return &_class_data_;
}

void XLoginReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<XLoginReq*>(&to_msg);
  auto& from = static_cast<const XLoginReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xmsg.XLoginReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_username().empty()) {
    _this->_internal_set_username(from._internal_username());
  }
  if (!from._internal_password().empty()) {
    _this->_internal_set_password(from._internal_password());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void XLoginReq::CopyFrom(const XLoginReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xmsg.XLoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool XLoginReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* XLoginReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void XLoginReq::InternalSwap(XLoginReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.username_, &other->_impl_.username_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.password_, &other->_impl_.password_, arena);
}

::google::protobuf::Metadata XLoginReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_XMsgCom_2eproto_getter, &descriptor_table_XMsgCom_2eproto_once,
      file_level_metadata_XMsgCom_2eproto[1]);
}
// ===================================================================

class XLoginRes::_Internal {
 public:
};

XLoginRes::XLoginRes(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:xmsg.XLoginRes)
}
inline PROTOBUF_NDEBUG_INLINE XLoginRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : token_(arena, from.token_),
        _cached_size_{0} {}

XLoginRes::XLoginRes(
    ::google::protobuf::Arena* arena,
    const XLoginRes& from)
    : ::google::protobuf::Message(arena) {
  XLoginRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.restype_ = from._impl_.restype_;

  // @@protoc_insertion_point(copy_constructor:xmsg.XLoginRes)
}
inline PROTOBUF_NDEBUG_INLINE XLoginRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : token_(arena),
        _cached_size_{0} {}

inline void XLoginRes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.restype_ = {};
}
XLoginRes::~XLoginRes() {
  // @@protoc_insertion_point(destructor:xmsg.XLoginRes)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void XLoginRes::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.token_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void XLoginRes::Clear() {
// @@protoc_insertion_point(message_clear_start:xmsg.XLoginRes)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_.ClearToEmpty();
  _impl_.restype_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* XLoginRes::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 28, 2> XLoginRes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_XLoginRes_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string token = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(XLoginRes, _impl_.token_)}},
    // .xmsg.XLoginRes.XLoginResType resType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(XLoginRes, _impl_.restype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(XLoginRes, _impl_.restype_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .xmsg.XLoginRes.XLoginResType resType = 1;
    {PROTOBUF_FIELD_OFFSET(XLoginRes, _impl_.restype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string token = 2;
    {PROTOBUF_FIELD_OFFSET(XLoginRes, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\0\5\0\0\0\0\0"
    "xmsg.XLoginRes"
    "token"
  }},
};

::uint8_t* XLoginRes::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xmsg.XLoginRes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .xmsg.XLoginRes.XLoginResType resType = 1;
  if (this->_internal_restype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_restype(), target);
  }

  // string token = 2;
  if (!this->_internal_token().empty()) {
    const std::string& _s = this->_internal_token();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "xmsg.XLoginRes.token");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xmsg.XLoginRes)
  return target;
}

::size_t XLoginRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xmsg.XLoginRes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string token = 2;
  if (!this->_internal_token().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_token());
  }

  // .xmsg.XLoginRes.XLoginResType resType = 1;
  if (this->_internal_restype() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_restype());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData XLoginRes::_class_data_ = {
    XLoginRes::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* XLoginRes::GetClassData() const {
  return &_class_data_;
}

void XLoginRes::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<XLoginRes*>(&to_msg);
  auto& from = static_cast<const XLoginRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xmsg.XLoginRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (from._internal_restype() != 0) {
    _this->_internal_set_restype(from._internal_restype());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void XLoginRes::CopyFrom(const XLoginRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xmsg.XLoginRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool XLoginRes::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* XLoginRes::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void XLoginRes::InternalSwap(XLoginRes* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
  swap(_impl_.restype_, other->_impl_.restype_);
}

::google::protobuf::Metadata XLoginRes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_XMsgCom_2eproto_getter, &descriptor_table_XMsgCom_2eproto_once,
      file_level_metadata_XMsgCom_2eproto[2]);
}
// ===================================================================

class XDirReq::_Internal {
 public:
};

XDirReq::XDirReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:xmsg.XDirReq)
}
inline PROTOBUF_NDEBUG_INLINE XDirReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : path_(arena, from.path_),
        _cached_size_{0} {}

XDirReq::XDirReq(
    ::google::protobuf::Arena* arena,
    const XDirReq& from)
    : ::google::protobuf::Message(arena) {
  XDirReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:xmsg.XDirReq)
}
inline PROTOBUF_NDEBUG_INLINE XDirReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : path_(arena),
        _cached_size_{0} {}

inline void XDirReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
XDirReq::~XDirReq() {
  // @@protoc_insertion_point(destructor:xmsg.XDirReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void XDirReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.path_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void XDirReq::Clear() {
// @@protoc_insertion_point(message_clear_start:xmsg.XDirReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.path_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* XDirReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 25, 2> XDirReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_XDirReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string path = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(XDirReq, _impl_.path_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string path = 1;
    {PROTOBUF_FIELD_OFFSET(XDirReq, _impl_.path_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\14\4\0\0\0\0\0\0"
    "xmsg.XDirReq"
    "path"
  }},
};

::uint8_t* XDirReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xmsg.XDirReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string path = 1;
  if (!this->_internal_path().empty()) {
    const std::string& _s = this->_internal_path();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "xmsg.XDirReq.path");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xmsg.XDirReq)
  return target;
}

::size_t XDirReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xmsg.XDirReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string path = 1;
  if (!this->_internal_path().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_path());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData XDirReq::_class_data_ = {
    XDirReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* XDirReq::GetClassData() const {
  return &_class_data_;
}

void XDirReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<XDirReq*>(&to_msg);
  auto& from = static_cast<const XDirReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xmsg.XDirReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_path().empty()) {
    _this->_internal_set_path(from._internal_path());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void XDirReq::CopyFrom(const XDirReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xmsg.XDirReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool XDirReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* XDirReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void XDirReq::InternalSwap(XDirReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.path_, &other->_impl_.path_, arena);
}

::google::protobuf::Metadata XDirReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_XMsgCom_2eproto_getter, &descriptor_table_XMsgCom_2eproto_once,
      file_level_metadata_XMsgCom_2eproto[3]);
}
// ===================================================================

class XDirRes_XDir::_Internal {
 public:
};

XDirRes_XDir::XDirRes_XDir(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:xmsg.XDirRes.XDir)
}
inline PROTOBUF_NDEBUG_INLINE XDirRes_XDir::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : filename_(arena, from.filename_),
        _cached_size_{0} {}

XDirRes_XDir::XDirRes_XDir(
    ::google::protobuf::Arena* arena,
    const XDirRes_XDir& from)
    : ::google::protobuf::Message(arena) {
  XDirRes_XDir* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.filesize_ = from._impl_.filesize_;

  // @@protoc_insertion_point(copy_constructor:xmsg.XDirRes.XDir)
}
inline PROTOBUF_NDEBUG_INLINE XDirRes_XDir::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : filename_(arena),
        _cached_size_{0} {}

inline void XDirRes_XDir::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.filesize_ = {};
}
XDirRes_XDir::~XDirRes_XDir() {
  // @@protoc_insertion_point(destructor:xmsg.XDirRes.XDir)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void XDirRes_XDir::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.filename_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void XDirRes_XDir::Clear() {
// @@protoc_insertion_point(message_clear_start:xmsg.XDirRes.XDir)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.ClearToEmpty();
  _impl_.filesize_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* XDirRes_XDir::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 34, 2> XDirRes_XDir::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_XDirRes_XDir_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 filesize = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(XDirRes_XDir, _impl_.filesize_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(XDirRes_XDir, _impl_.filesize_)}},
    // string filename = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(XDirRes_XDir, _impl_.filename_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string filename = 1;
    {PROTOBUF_FIELD_OFFSET(XDirRes_XDir, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 filesize = 2;
    {PROTOBUF_FIELD_OFFSET(XDirRes_XDir, _impl_.filesize_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\21\10\0\0\0\0\0\0"
    "xmsg.XDirRes.XDir"
    "filename"
  }},
};

::uint8_t* XDirRes_XDir::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xmsg.XDirRes.XDir)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string filename = 1;
  if (!this->_internal_filename().empty()) {
    const std::string& _s = this->_internal_filename();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "xmsg.XDirRes.XDir.filename");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int32 filesize = 2;
  if (this->_internal_filesize() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_filesize(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xmsg.XDirRes.XDir)
  return target;
}

::size_t XDirRes_XDir::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xmsg.XDirRes.XDir)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string filename = 1;
  if (!this->_internal_filename().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_filename());
  }

  // int32 filesize = 2;
  if (this->_internal_filesize() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_filesize());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData XDirRes_XDir::_class_data_ = {
    XDirRes_XDir::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* XDirRes_XDir::GetClassData() const {
  return &_class_data_;
}

void XDirRes_XDir::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<XDirRes_XDir*>(&to_msg);
  auto& from = static_cast<const XDirRes_XDir&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xmsg.XDirRes.XDir)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (from._internal_filesize() != 0) {
    _this->_internal_set_filesize(from._internal_filesize());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void XDirRes_XDir::CopyFrom(const XDirRes_XDir& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xmsg.XDirRes.XDir)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool XDirRes_XDir::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* XDirRes_XDir::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void XDirRes_XDir::InternalSwap(XDirRes_XDir* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
        swap(_impl_.filesize_, other->_impl_.filesize_);
}

::google::protobuf::Metadata XDirRes_XDir::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_XMsgCom_2eproto_getter, &descriptor_table_XMsgCom_2eproto_once,
      file_level_metadata_XMsgCom_2eproto[4]);
}
// ===================================================================

class XDirRes::_Internal {
 public:
};

XDirRes::XDirRes(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:xmsg.XDirRes)
}
inline PROTOBUF_NDEBUG_INLINE XDirRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : dirs_{visibility, arena, from.dirs_},
        _cached_size_{0} {}

XDirRes::XDirRes(
    ::google::protobuf::Arena* arena,
    const XDirRes& from)
    : ::google::protobuf::Message(arena) {
  XDirRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.restype_ = from._impl_.restype_;

  // @@protoc_insertion_point(copy_constructor:xmsg.XDirRes)
}
inline PROTOBUF_NDEBUG_INLINE XDirRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : dirs_{visibility, arena},
        _cached_size_{0} {}

inline void XDirRes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.restype_ = {};
}
XDirRes::~XDirRes() {
  // @@protoc_insertion_point(destructor:xmsg.XDirRes)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void XDirRes::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void XDirRes::Clear() {
// @@protoc_insertion_point(message_clear_start:xmsg.XDirRes)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.dirs_.Clear();
  _impl_.restype_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* XDirRes::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> XDirRes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_XDirRes_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .xmsg.XDirRes.XDir dirs = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(XDirRes, _impl_.dirs_)}},
    // .xmsg.XDirRes.XDirType resType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(XDirRes, _impl_.restype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(XDirRes, _impl_.restype_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .xmsg.XDirRes.XDirType resType = 1;
    {PROTOBUF_FIELD_OFFSET(XDirRes, _impl_.restype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // repeated .xmsg.XDirRes.XDir dirs = 2;
    {PROTOBUF_FIELD_OFFSET(XDirRes, _impl_.dirs_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::xmsg::XDirRes_XDir>()},
  }}, {{
  }},
};

::uint8_t* XDirRes::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xmsg.XDirRes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .xmsg.XDirRes.XDirType resType = 1;
  if (this->_internal_restype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_restype(), target);
  }

  // repeated .xmsg.XDirRes.XDir dirs = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_dirs_size()); i < n; i++) {
    const auto& repfield = this->_internal_dirs().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xmsg.XDirRes)
  return target;
}

::size_t XDirRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xmsg.XDirRes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .xmsg.XDirRes.XDir dirs = 2;
  total_size += 1UL * this->_internal_dirs_size();
  for (const auto& msg : this->_internal_dirs()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // .xmsg.XDirRes.XDirType resType = 1;
  if (this->_internal_restype() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_restype());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData XDirRes::_class_data_ = {
    XDirRes::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* XDirRes::GetClassData() const {
  return &_class_data_;
}

void XDirRes::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<XDirRes*>(&to_msg);
  auto& from = static_cast<const XDirRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xmsg.XDirRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_dirs()->MergeFrom(
      from._internal_dirs());
  if (from._internal_restype() != 0) {
    _this->_internal_set_restype(from._internal_restype());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void XDirRes::CopyFrom(const XDirRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xmsg.XDirRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool XDirRes::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* XDirRes::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void XDirRes::InternalSwap(XDirRes* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.dirs_.InternalSwap(&other->_impl_.dirs_);
  swap(_impl_.restype_, other->_impl_.restype_);
}

::google::protobuf::Metadata XDirRes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_XMsgCom_2eproto_getter, &descriptor_table_XMsgCom_2eproto_once,
      file_level_metadata_XMsgCom_2eproto[5]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace xmsg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
